### ISSUE TITLE
Bad Access

### ISSUE THREAD

**Issue by roffiel** [RatioInnovacion/Pintumex#1]
* Este error ocurre al probar la app en iPhone, en la 2 pantalla de instrucciones:

![captura de pantalla 2015-10-12 a las 19 23 02](https://cloud.githubusercontent.com/assets/11275558/10442368/3bab11c0-7117-11e5-9cc4-877ea8aafc8f.png)

```
Pintumex`GetCurrentTargetWidth:
    0x10109c1e8 <+0>:  adrp   x8, 8832
    0x10109c1ec <+4>:  add    x8, x8, #400
    0x10109c1f0 <+8>:  ldr    x8, [x8]
->  0x10109c1f4 <+12>: ldr    w0, [x8, #8]
    0x10109c1f8 <+16>: ret    
```

**Comment by roffiel** [comment]
*holi
*holi*
**holi**

**Comment by RaschidGithub** [comment]
Se arregló seleccionando **OpenGL 2.0** e **IL2CPP** en las opciones del Building para iOS.

Referencia:
https://developer.vuforia.com/forum/ios/no-camera-image-unity-ipad-air-2
